version: "3.9"

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--configfile=/etc/traefik/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - external-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ../config:/app/config
    networks:
      - external-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`backend.pixelpickle.net`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=80"

networks:
  external-net:
    name: external-net
    driver: bridge

